version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tmp/
hooks:
  ApplicationStop:
    - location: scripts/server_stop
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/install_dependencies_app_user
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/app_setup
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start
      timeout: 300
      runas: ec2-user
