default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: tpm_development

test:
  <<: *default
  database: tpm_test

production:
  <<: *default
  database: tpm_production
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
